import {describe,it,expect,vi,beforeEach,afterEach} from 'vitest';
const mock=vi.hoisted(()=>({getTransaction:vi.fn(),readContract:vi.fn()}));
vi.mock('genlayer-js',()=>({chains:{studioDevnet:{id:61997}},createClient:()=>({getTransaction:mock.getTransaction,readContract:mock.readContract})}));
import {indexOne} from '../services/gateway/src/index';
const hash='0x'+'a'.repeat(64) as `0x${string}`;
const addr=(x:string)=>'0x'+x.repeat(40);
const contracts={participants:addr('1'),agreements:addr('2'),events:addr('3'),evidence:addr('4'),consensus:addr('5'),obligations:addr('6')};
const env:any={GENLAYER_RPC:'https://rpc.example',CONTRACTS_JSON:JSON.stringify(contracts),SUPABASE_URL:'https://db.example',SUPABASE_SERVICE_ROLE_KEY:'service'};
const result={cause:'MAINTENANCE_DEFICIENCY',responsible_org:'SP',start_minute:100,end_minute:340,clause_ids:['A1:1:credit'],excluded_clause_ids:[],evidence_ids:['E1']};
const event={id:'EV1',asset:'K401',operator:'OP',parties:['OP','SP'],links:[{id:'A1',version:1}],closeAfter:'2026-10-01T00:00:00Z',openedMinute:100,finalResult:JSON.stringify(result)};
beforeEach(()=>{const store:any[]=[];vi.stubGlobal('fetch',async(input:any,init:RequestInit)=>{const url=new URL(String(input));if(url.hostname==='rpc.example')return new Response(JSON.stringify({result:{hash,tx_id:hash,recipient:contracts.events,status:'FINALIZED',txExecutionResultName:'FINISHED_WITH_RETURN',fees:{deposit:'100',consumed:{executionConsumed:'50',messageFeesConsumed:'10'}},roundData:[{round:0}]}}));store.push({path:url.pathname,method:init.method,body:init.body});return new Response('{}')});mock.getTransaction.mockReset().mockResolvedValue({statusName:'FINALIZED',txExecutionResultName:'FINISHED_WITH_RETURN',recipient:contracts.events,txDataDecoded:{callData:{'':'record_finalized',args:['EV1',JSON.stringify(result)]}}});mock.readContract.mockReset().mockImplementation(({address,functionName,args}:any)=>{if(address===contracts.events)return JSON.stringify(event);if(address===contracts.evidence&&functionName==='manifest')return JSON.stringify({ids:['E1'],digest:'a'.repeat(64)});if(address===contracts.evidence)return JSON.stringify({id:'E1',event:'EV1',organisation:'SP',kind:'CMMS',digest:'b'.repeat(64)});if(address===contracts.obligations)return '';if(address===contracts.agreements)return JSON.stringify({agreement:'A1',version:1,operator:'OP',counterparty:'SP',accepted:true,policy:{type:'MAINTENANCE_SLA'}});return ''});(globalThis as any).__store=store});
afterEach(()=>vi.unstubAllGlobals());
describe('verified indexing path',()=>{
 it('indexes a finalized child and reconstructs canonical state and fee rounds',async()=>{const indexed=await indexOne(env,hash);expect(indexed).toEqual({event:'EV1',method:'record_finalized'});const writes=(globalThis as any).__store;expect(writes.some((w:any)=>w.path.endsWith('/indexed_determinations')&&JSON.parse(w.body).result.cause==='MAINTENANCE_DEFICIENCY')).toBe(true);expect(writes.some((w:any)=>w.path.endsWith('/tracked_transactions')&&JSON.parse(w.body).fee_outcome.deposit==='100')).toBe(true)});
 it('rejects forged child postcondition and does not index a verdict',async()=>{mock.readContract.mockImplementation(({address,functionName}:any)=>address===contracts.events?JSON.stringify({...event,finalResult:''}):functionName==='manifest'?JSON.stringify({ids:[],digest:''}):'');await expect(indexOne(env,hash)).rejects.toThrow('Finalized child not delivered');expect((globalThis as any).__store.some((w:any)=>w.path.endsWith('/indexed_determinations'))).toBe(false)});
 it('rejects a receipt from another configured method recipient',async()=>{mock.getTransaction.mockResolvedValue({statusName:'FINALIZED',txExecutionResultName:'FINISHED_WITH_RETURN',recipient:contracts.consensus,txDataDecoded:{callData:{'':'record_finalized',args:['EV1']}}});await expect(indexOne(env,hash)).rejects.toThrow('Recipient')});
});
