import {describe,it,expect} from 'vitest';
import {worstCaseProfile,assertRepresentativeCoverage} from '../scripts/fee-profile-policy.mjs';
import {routeContext,sectionToPath} from '../apps/web/src/lib/routes.ts';
import {appealable} from '../apps/web/src/components/event-appeal.tsx';
import {assertDeterminationContext,identifyIntent} from '../services/gateway/src/indexer.ts';
const address=n=>'0x'+String(n).repeat(40);
const contracts={participants:address(1),agreements:address(2),events:address(3),evidence:address(4),consensus:address(5),obligations:address(6)};
const tx=(method,event,recipient=contracts.consensus)=>({recipient,txDataDecoded:{callData:{'':method,args:[event]}}});
describe('route, event appeals and worst-case fee changes',()=>{
 it('maps real App Router sections and event detail paths',()=>{expect(routeContext('/events/EV1')).toEqual({section:'Operational events',eventId:'EV1'});expect(routeContext('/agreements').section).toBe('Agreements');expect(sectionToPath['Audit & verification']).toBe('/audit')});
 it('binds an ACCEPTED appeal to a verified determination for the selected event',()=>{expect(assertDeterminationContext(tx('determine','EV1'),contracts,'EV1').method).toBe('determine');expect(appealable({hash:'0xabc',method:'determine',status:'ACCEPTED',round:1})).toBe(true);expect(appealable({hash:'0xabc',method:'determine',status:'FINALIZED',round:2})).toBe(false);expect(()=>assertDeterminationContext(tx('determine','EV2'),contracts,'EV1')).toThrow();expect(()=>assertDeterminationContext(tx('apply','EV1',contracts.obligations),contracts,'EV1')).toThrow();expect(()=>assertDeterminationContext(tx('determine','EV1',contracts.events),contracts,'EV1')).toThrow()});
 it('accepts pending intent only for tracking, never as finalized state',()=>{expect(identifyIntent(tx('determine','EV1'),contracts).eventId).toBe('EV1')});
 it('takes the maximum independently per fee dimension rather than the last sample',()=>{const p=worstCaseProfile([{leaderTimeunitsAllocation:'90',validatorTimeunitsAllocation:'20',executionBudgetPerRound:'50',totalMessageFees:'100',rotationsPerRound:'2'},{leaderTimeunitsAllocation:'40',validatorTimeunitsAllocation:'80',executionBudgetPerRound:'70',totalMessageFees:'10',rotationsPerRound:'1'}]);expect(p).toMatchObject({leaderTimeunitsAllocation:'90',validatorTimeunitsAllocation:'80',executionBudgetPerRound:'70',totalMessageFees:'100',rotationsPerRound:'2',sampleCount:2})});
 it('rejects empty or invalid fee measurements',()=>{expect(()=>worstCaseProfile([])).toThrow();expect(()=>worstCaseProfile([{leaderTimeunitsAllocation:'-1',validatorTimeunitsAllocation:'0',executionBudgetPerRound:'0',totalMessageFees:'0'}])).toThrow()});
 it('requires distinct receipt hashes and scenarios for expensive fee cases',()=>{const methods=['open_event','submit','determine','apply'];let n=1;const cases=methods.flatMap(method=>[{hash:'0x'+String(n++).padStart(64,'0'),method,scenario:'small'},{hash:'0x'+String(n++).padStart(64,'0'),method,scenario:'large'}]);expect(()=>assertRepresentativeCoverage(cases)).not.toThrow();expect(()=>assertRepresentativeCoverage(cases.filter(x=>!(x.method==='determine'&&x.scenario==='large')))).toThrow('determine');expect(()=>assertRepresentativeCoverage(cases.map(x=>({...x,scenario:'same'})))).toThrow('distinct');expect(()=>assertRepresentativeCoverage(cases.map(x=>({...x,hash:cases[0].hash})))).toThrow('Duplicate transaction receipt')});
});
