'use client';
import {useEffect,useState} from 'react';
import {appeal,type Address,type ActionState} from '../lib/genlayer';
export type ProtocolEntry={hash:string;method:string;status:string;execution?:string;round:number;detail?:{votesCommitted?:number;votesRevealed?:number};rounds?:unknown;fees?:unknown};
export function appealable(entry:ProtocolEntry){return entry.method==='determine'&&entry.status==='ACCEPTED'}
export function EventAppeal({eventId,token,gateway,account,onState,onNotice}:{eventId:string;token:string;gateway:string;account:Address|null;onState:(s:ActionState)=>void;onNotice:(s:string)=>void}){
 const [history,setHistory]=useState<ProtocolEntry[]>([]),[selected,setSelected]=useState(''),[charge,setCharge]=useState<string|null>(null),[loading,setLoading]=useState(false);
 async function refresh(){if(!token)return;setLoading(true);try{const r=await fetch(`${gateway}/v1/events/${eventId}/protocol`,{headers:{Authorization:`Bearer ${token}`}});const data=await r.json();if(!r.ok)throw Error(data.error||'Protocol history unavailable');setHistory(data.history);if(!data.history.some((x:ProtocolEntry)=>x.hash===selected))setSelected(data.history.find((x:ProtocolEntry)=>appealable(x))?.hash||'')}catch(e){onNotice(String(e))}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[eventId,token]);
 const entry=history.find(x=>x.hash===selected);
 async function quote(){try{if(!account||!entry||!appealable(entry))throw Error('Select an ACCEPTED determination for this event');const q=await appeal((window as any).ethereum,account,entry.hash as Address);setCharge(q.charge.toString())}catch(e){onNotice(String(e))}}
 async function submit(){try{if(!account||!entry||!appealable(entry)||!charge)throw Error('Appeal quote is unavailable');const q=await appeal((window as any).ethereum,account,entry.hash as Address);if(q.charge.toString()!==charge)throw Error('Appeal charge changed; quote again');onState({phase:'signing'});const hash=await q.submit();onState({phase:'pending',hash});setCharge(null);await refresh()}catch(e){onNotice(String(e))}}
 return <div className="detail-section"><h4>Consensus and appeals · {eventId}</h4><button className="secondary" onClick={refresh} disabled={loading||!token}>Refresh event rounds</button>{history.length===0?<p>No tracked determination for this event yet. An ACCEPTED determination can be appealed before finalization.</p>:history.map(item=><div className="linked" key={item.hash}><label><input type="radio" name="event-determination" checked={selected===item.hash} onChange={()=>{setSelected(item.hash);setCharge(null)}}/> {item.method} · round {item.round} · {item.status} · {item.execution||'execution pending'}</label><small>{item.hash.slice(0,10)}… · votes {String(item.detail?.votesCommitted??'—')}/{String(item.detail?.votesRevealed??'—')}</small></div>)}{entry?<div className="button-row"><button className="secondary" onClick={quote} disabled={!account||!appealable(entry)}>Quote appeal</button>{charge?<button className="primary" onClick={submit} disabled={!appealable(entry)}>Appeal · {charge} wei</button>:null}</div>:null}<p>ACCEPTED is appealable. Effects require FINALIZED, successful execution and delivered child state.</p></div>
}
