alter table tracked_transactions alter column event_id drop not null;
alter table tracked_transactions add column if not exists contract_name text;
alter table tracked_transactions add column if not exists method_name text;
alter table tracked_transactions add column if not exists error text;
alter table indexed_events add column if not exists parties jsonb not null default '[]'::jsonb;
alter table indexed_events add column if not exists links jsonb not null default '[]'::jsonb;
alter table indexed_events add column if not exists close_after timestamptz;
alter table indexed_events add column if not exists opened_minute bigint;
create table if not exists indexed_evidence (evidence_id text primary key, event_id text not null, organisation_id text not null, kind text not null, digest text not null, url text not null, observed_at text not null, target_id text, source_tx_hash text references tracked_transactions(tx_hash), verified_at timestamptz not null default now());
create table if not exists indexed_determinations (event_id text primary key, cause text not null, responsible_org text, start_minute bigint, end_minute bigint, result jsonb not null, source_tx_hash text references tracked_transactions(tx_hash), verified_at timestamptz not null default now());
create table if not exists indexed_effects (event_id text not null, agreement_id text not null, version integer not null, mode text not null, outcomes jsonb not null, source_tx_hash text references tracked_transactions(tx_hash), verified_at timestamptz not null default now(), primary key(event_id,agreement_id,version));
create table if not exists indexed_agreements (agreement_id text not null, version integer not null, operator_id text not null, counterparty_id text not null, accepted boolean not null, policy jsonb not null, source_tx_hash text references tracked_transactions(tx_hash), verified_at timestamptz not null default now(), primary key(agreement_id,version));
create table if not exists index_failures (tx_hash text primary key, reason text not null, attempted_at timestamptz not null default now(), attempts integer not null default 1);
alter table indexed_evidence enable row level security;alter table indexed_determinations enable row level security;alter table indexed_effects enable row level security;alter table indexed_agreements enable row level security;alter table index_failures enable row level security;
create index if not exists indexed_events_parties_gin on indexed_events using gin(parties);
create index if not exists indexed_evidence_event on indexed_evidence(event_id);
create table if not exists indexed_organisations (organisation_id text primary key, record jsonb not null, source_tx_hash text references tracked_transactions(tx_hash), verified_at timestamptz not null default now());
alter table indexed_organisations enable row level security;
alter table indexed_events add column if not exists consensus_tx_hash text;
alter table indexed_events add column if not exists child_tx_hash text;
create table if not exists assets (asset_id text primary key check(asset_id ~ '^[A-Za-z0-9_-]{1,64}$'), organisation_id text not null references organisations(id), description text not null, equipment_class text not null, facility text not null, criticality text not null check(criticality in ('LOW','MEDIUM','HIGH','SAFETY_CRITICAL')), created_at timestamptz not null default now());
alter table assets enable row level security;
create policy "asset members" on assets for select to authenticated using(exists(select 1 from user_organisations u where u.user_id=auth.uid() and u.organisation_id=assets.organisation_id));
alter table notifications add column if not exists notification_key text unique;
alter table tracked_transactions add column if not exists fee_outcome jsonb;
alter table tracked_transactions add column if not exists rounds jsonb;
alter table tracked_transactions add column if not exists recipient text;
create table if not exists decision_exports (digest text primary key check(digest ~ '^[0-9a-f]{64}$'), event_id text not null, object_key text not null unique, created_by uuid not null, created_at timestamptz not null default now());
alter table decision_exports enable row level security;
