import { readFileSync,writeFileSync,existsSync } from 'node:fs';
import { createClient,createAccount,chains,isSuccessful } from 'genlayer-js';
const names=['participants','agreements','events','evidence','consensus','obligations'];
const files=['participant_registry.py','agreement_registry.py','event_registry.py','evidence_registry.py','event_consensus.py','obligation_engine.py'];
const argsFor={participants:()=>[],agreements:x=>[x.participants],events:x=>[x.participants,x.agreements],evidence:x=>{if(!process.env.GATEWAY_BASE_URL)throw Error('GATEWAY_BASE_URL ending /v1/evidence/ required');return [x.participants,x.events,process.env.GATEWAY_BASE_URL]},consensus:x=>[x.events,x.evidence,x.agreements],obligations:x=>[x.events,x.agreements]};
const priv=process.env.DEPLOYER_PRIVATE_KEY;if(!/^0x[0-9a-fA-F]{64}$/.test(priv??''))throw Error('DEPLOYER_PRIVATE_KEY required for local deployment only');
const account=createAccount(priv);const client=createClient({chain:chains.studioDevnet,endpoint:'https://studio-dev.genlayer.com/api',account});
const profile=JSON.parse(readFileSync('apps/web/public/fee-profile.json','utf8'));
if(!['network-quoted-bootstrap','simulated','measured'].includes(profile.status)||profile.network!=='studio-dev'||profile.chainId!==61997)throw Error('Network-quoted Studio Dev bootstrap profile required. Run profile-fees.mjs bootstrap.');
const path='deployment.studio-dev.json';const manifest=existsSync(path)?JSON.parse(readFileSync(path,'utf8')):{chainId:61997,contracts:{},transactions:{}};
manifest.transactions??={};
function save(){writeFileSync(path,JSON.stringify(manifest,null,2)+'\n')}
async function quote(entry){if(!entry)throw Error('Fee profile entry missing');const rotations=BigInt(entry.rotationsPerRound??'1');const q=await client.estimateTransactionFees({leaderTimeunitsAllocation:BigInt(entry.leaderTimeunitsAllocation),validatorTimeunitsAllocation:BigInt(entry.validatorTimeunitsAllocation),executionBudgetPerRound:BigInt(entry.executionBudgetPerRound),totalMessageFees:BigInt(entry.totalMessageFees??0),appealRounds:1n,rotations:[rotations,rotations]});return {distribution:q.distribution,feeValue:q.feeValue}}
async function final(hash){try{await client.waitForFinalization({hash})}catch(error){console.warn(`Finality wait ended before completion for ${hash}; resuming the submitted transaction`,error instanceof Error?error.message:String(error))}let receipt;for(let attempt=0;attempt<120;attempt++){receipt=await client.getTransaction({hash});if(receipt.lifecycle?.state==='finalized'||receipt.lifecycle?.state==='appealed')break;await new Promise(resolve=>setTimeout(resolve,5000))}if(!receipt||receipt.lifecycle?.state!=='finalized'||!isSuccessful(receipt)||receipt.txExecutionResultName!=='FINISHED_WITH_RETURN')throw Error(`Unsuccessful or still-pending transaction ${hash}: ${receipt?.lifecycle?.state??receipt?.status}/${receipt?.txExecutionResultName}`);return receipt}
async function resetAfterNetworkReset(){manifest.staleDeployments??=[];manifest.staleDeployments.push({detectedAt:new Date().toISOString(),network:'studio-dev',chainId:61997,contracts:{...manifest.contracts}});manifest.contracts={};manifest.deployments={};manifest.transactions={};manifest.binding={status:'unbound'};save()}
async function deploy(name,file){if(manifest.contracts[name]){const existing=await client.getContractCode(manifest.contracts[name]);if(existing)return;console.warn(`Recorded ${name} deployment is absent on Studio Dev; preserving the prior map and starting a fresh six-contract deployment`);await resetAfterNetworkReset()}let hash=manifest.transactions[name];if(!hash){hash=await client.deployContract({code:new Uint8Array(readFileSync(`contracts/${file}`)),args:argsFor[name](manifest.contracts),fees:await quote(profile.deploy)});manifest.transactions[name]=hash;save()}
const receipt=await final(hash);const address=receipt.txDataDecoded?.contractAddress??receipt.recipient;if(!address)throw Error(`Missing deployed address for ${name}`);manifest.contracts[name]=address;manifest.deployments??={};manifest.deployments[name]={address,txHash:hash,deployer:account.address,network:'studio-dev',chainId:61997,status:'FINALIZED',execution:'FINISHED_WITH_RETURN',feeDeposit:String(receipt.fees?.deposit??''),feeConsumed:String(receipt.fees?.consumed?.executionConsumed??''),feeRefunded:receipt.fees?.deposit&&receipt.fees?.consumed?.executionConsumed?(BigInt(receipt.fees.deposit)-BigInt(receipt.fees.consumed.executionConsumed)-BigInt(receipt.fees.consumed.messageFeesConsumed??0)).toString():''};save();console.log(name,address,hash)}
async function write(key,address,method,args){if(manifest.transactions[key+'_final'])return manifest.transactions[key];let hash=manifest.transactions[key];if(!hash){hash=await client.writeContract({address,functionName:method,args,fees:await quote(profile.methods[method])});manifest.transactions[key]=hash;save()}await final(hash);manifest.transactions[key+'_final']=true;save();console.log(method,hash);return hash}
const command=process.argv[2];if(command==='deploy'){for(let i=0;i<names.length;i++)await deploy(names[i],files[i]);if(manifest.binding?.status!=='bound'){const hash=await write('bind_consensus',manifest.contracts.events,'bind_consensus',[manifest.contracts.consensus]);manifest.binding={status:'bound',txHash:hash};save()}console.log('Deployment complete. Use the contracts map for NEXT_PUBLIC_CONTRACTS_JSON.')}else if(command==='verify'){for(const name of names){const addr=manifest.contracts[name];if(!addr)throw Error(`${name} missing`);const code=await client.getContractCode(addr);if(!code)throw Error(`${name} code unavailable`);console.log(name,addr,'code present')}const event=await client.readContract({address:manifest.contracts.events,functionName:'get',args:['NON_EXISTENT']});console.log('Registry read:',event)}else if(command==='seed'){if(names.some(n=>!manifest.contracts[n]))throw Error('Deploy first');const P=manifest.contracts.participants,A=manifest.contracts.agreements,E=manifest.contracts.events;
 const orgs=[['OP-WR','Warri River Operator',process.env.OPERATOR_SIGNER,'OPERATOR'],['MNT-SP','Rotating Equipment Service',process.env.CONTRACTOR_SIGNER,'SERVICE_PROVIDER'],['OEM-K','Compressor OEM',process.env.OEM_SIGNER,'OEM'],['JV-PARTNER','Joint Venture Partner',process.env.JV_SIGNER,'THIRD_PARTY'],['INSPECTOR-1','Independent Inspection Organisation',process.env.INSPECTOR_SIGNER,'INSPECTOR']];for(const [id,name,signer,role] of orgs){if(!/^0x[0-9a-fA-F]{40}$/.test(signer??''))throw Error(`Signer missing for ${id}`);const existing=await client.readContract({address:P,functionName:'get',args:[id]});if(existing){const record=JSON.parse(existing);if(record.signer.toLowerCase()!==signer.toLowerCase()||record.role!==role)throw Error(`Organisation ${id} already exists with a different signer or role`);console.log('already registered',id);continue}await write('register_'+id,P,'register',[id,name,signer,role])}
 console.log('Organisation records seeded. Create agreement with operator signer and accept with counterparty signer; then open event and submit evidence using those injected signers.');
}else throw Error('Usage: node scripts/protocol.mjs deploy|verify|seed');
