import { z } from 'zod';
const id=z.string().regex(/^[A-Za-z0-9_-]{1,64}$/);
export const packageSchema=z.object({schemaVersion:z.literal(1),eventId:id,evidenceId:id,organisation:id,type:z.enum(['HISTORIAN','CMMS','ERP','OPC_UA','OEM','LAB','INSPECTION','MANUAL','CHALLENGE']),observedAt:z.string().datetime({offset:true}),source:z.string().min(1).max(180),targetEvidenceId:id.optional(),facts:z.array(z.object({field:z.string().min(1).max(80),value:z.string().max(800),unit:z.string().max(30).optional(),at:z.string().datetime({offset:true}).optional()}).strict()).min(1).max(10),redactions:z.array(z.string().max(100)).max(20)}).strict().superRefine((v,ctx)=>{if((v.type==='CHALLENGE')!==Boolean(v.targetEvidenceId))ctx.addIssue({code:'custom',message:'Challenge target and type must coincide'})});
export type EvidencePackage=z.infer<typeof packageSchema>;
export type Context={eventId:string;evidenceId:string;organisation:string;source:string;redactions?:string[]};
export interface SourceAdapter<T>{type:EvidencePackage['type'];convert(raw:T,context:Context):EvidencePackage}
const base=(c:Context,type:EvidencePackage['type'],observedAt:string,facts:EvidencePackage['facts']):EvidencePackage=>packageSchema.parse({schemaVersion:1,eventId:c.eventId,evidenceId:c.evidenceId,organisation:c.organisation,type,observedAt,source:c.source,redactions:c.redactions??[],facts});
export const historian:SourceAdapter<{tag:string;points:Array<{time:string;value:number;unit:string}>}>={type:'HISTORIAN',convert(raw,c){if(!raw.tag||!raw.points.length||raw.points.length>10)throw Error('Invalid historian series');return base(c,'HISTORIAN',raw.points[0].time,raw.points.map(p=>({field:raw.tag,value:String(p.value),unit:p.unit,at:p.time})))}};
export const cmms:SourceAdapter<{workOrder:string;asset:string;openedAt:string;closedAt:string;task:string;result:string}>={type:'CMMS',convert(r,c){return base(c,'CMMS',r.closedAt,[{field:'work_order',value:r.workOrder},{field:'asset',value:r.asset},{field:'task',value:r.task},{field:'result',value:r.result},{field:'opened_at',value:r.openedAt}])}};
export const erp:SourceAdapter<{document:string;postedAt:string;counterparty:string;material:string;quantity:number;unit:string}>={type:'ERP',convert(r,c){return base(c,'ERP',r.postedAt,[{field:'document',value:r.document},{field:'counterparty',value:r.counterparty},{field:'material',value:r.material},{field:'quantity',value:String(r.quantity),unit:r.unit}])}};
export const opcUa:SourceAdapter<{nodeId:string;sourceTimestamp:string;statusCode:string;value:string;unit:string}>={type:'OPC_UA',convert(r,c){return base(c,'OPC_UA',r.sourceTimestamp,[{field:'node_id',value:r.nodeId},{field:'status_code',value:r.statusCode},{field:'reading',value:r.value,unit:r.unit}])}};
export const oem:SourceAdapter<{serial:string;reportId:string;issuedAt:string;diagnosis:string;warrantyPosition:string}>={type:'OEM',convert(r,c){return base(c,'OEM',r.issuedAt,[{field:'serial',value:r.serial},{field:'report_id',value:r.reportId},{field:'diagnosis',value:r.diagnosis},{field:'warranty_position',value:r.warrantyPosition}])}};
export const laboratory:SourceAdapter<{sampleId:string;collectedAt:string;reportedAt:string;method:string;analyte:string;result:string;unit:string}>={type:'LAB',convert(r,c){return base(c,'LAB',r.reportedAt,[{field:'sample_id',value:r.sampleId},{field:'collected_at',value:r.collectedAt},{field:'method',value:r.method},{field:r.analyte,value:r.result,unit:r.unit}])}};
export const inspection:SourceAdapter<{inspectionId:string;inspectedAt:string;asset:string;finding:string;standard:string}>={type:'INSPECTION',convert(r,c){return base(c,'INSPECTION',r.inspectedAt,[{field:'inspection_id',value:r.inspectionId},{field:'asset',value:r.asset},{field:'finding',value:r.finding},{field:'standard',value:r.standard}])}};
export const adapters={historian,cmms,erp,opcUa,oem,laboratory,inspection};
