import { packageSchema, type EvidencePackage } from './adapters';
import {chainClient,identifyIntentAcross,contractMaps,assertDeterminationContext,readVerifiedEvent,rawReceipt,verifiedReceipt,type ContractMap} from './indexer';
import type {R2Bucket,ScheduledController,ExecutionContext} from '@cloudflare/workers-types';
export interface Env {EVIDENCE:R2Bucket;SUPABASE_URL:string;SUPABASE_SERVICE_ROLE_KEY:string;SUPABASE_ANON_KEY:string;ORGANISATION_HMAC_KEYS:string;GENLAYER_RPC:string;CONTRACTS_JSON:string;CONTRACTS_ARCHIVE_JSON?:string;INTERNAL_CRON_TOKEN:string;ALLOWED_ORIGIN:string}
const encoder=new TextEncoder();
function canonical(v:unknown):string {if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';if(v&&typeof v==='object')return '{'+Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,value])=>JSON.stringify(k)+':'+canonical(value)).join(',')+'}';return JSON.stringify(v)}
export function canonicalBytes(v:unknown){return encoder.encode(canonical(v))}
export async function sha256(b:Uint8Array){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',Uint8Array.from(b)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
function response(data:unknown,status=200,origin=''){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':origin}})}
async function db(env:Env,path:string,init:RequestInit={}){const headers=new Headers(init.headers);headers.set('apikey',env.SUPABASE_SERVICE_ROLE_KEY);headers.set('content-type','application/json');if(env.SUPABASE_SERVICE_ROLE_KEY.startsWith('sb_secret_'))headers.delete('Authorization');else headers.set('Authorization',`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`);const r=await fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{...init,headers});if(!r.ok)throw Error(`Database request failed (${r.status})`);return r}
async function rows<T>(env:Env,path:string){return await db(env,path).then(r=>r.json() as Promise<T[]>)}
async function upsert(env:Env,table:string,value:unknown){await db(env,table,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(value)})}
export type Principal={userId:string;organisations:Array<{organisation_id:string;application_role:string}>};
export async function principal(req:Request,env:Env):Promise<Principal>{const bearer=req.headers.get('authorization')?.match(/^Bearer (.+)$/)?.[1];if(!bearer)throw Error('Authentication required');const r=await fetch(`${env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:env.SUPABASE_ANON_KEY,Authorization:`Bearer ${bearer}`}});if(!r.ok)throw Error('Invalid session');const user=await r.json() as {id?:string};if(!user.id)throw Error('Invalid identity');const memberships=await rows<{organisation_id:string;application_role:string}>(env,`user_organisations?user_id=eq.${encodeURIComponent(user.id)}&select=organisation_id,application_role`);return {userId:user.id,organisations:memberships}}
function membership(p:Principal,org:string,write=false){return p.organisations.some(x=>x.organisation_id===org&&(!write||['preparer','signer'].includes(x.application_role)))}
async function hmac(req:Request,bytes:Uint8Array,env:Env,org:string){const time=Number(req.headers.get('x-fieldledger-timestamp'));const sig=req.headers.get('x-fieldledger-signature')??'';if(!Number.isFinite(time)||Math.abs(Date.now()-time)>300000||!/^[0-9a-f]{64}$/.test(sig))return false;const secret=(JSON.parse(env.ORGANISATION_HMAC_KEYS||'{}') as Record<string,string>)[org];if(!secret)return false;const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=await sha256(bytes);const expected=[...new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(`${time}.${digest}`)))].map(x=>x.toString(16).padStart(2,'0')).join('');let diff=0;for(let i=0;i<64;i++)diff|=expected.charCodeAt(i)^sig.charCodeAt(i);return diff===0}
async function ingest(req:Request,env:Env,origin:string,manual:boolean){const bytes=new Uint8Array(await req.arrayBuffer());if(bytes.length>16384)return response({error:'Request exceeds 16 KiB parsing limit'},413,origin);let data:EvidencePackage;try{data=packageSchema.parse(JSON.parse(new TextDecoder().decode(bytes)))}catch{return response({error:'Invalid package'},422,origin)}
 if(manual){const p=await principal(req,env);if(!membership(p,data.organisation,true)||!['MANUAL','CHALLENGE'].includes(data.type))return response({error:'Organisation role denied'},403,origin)}else if(!await hmac(req,bytes,env,data.organisation))return response({error:'Source authentication failed'},401,origin);
 const event=await readVerifiedEvent(env,data.eventId);
 if(![...event.event.parties,...event.event.externalSources].includes(data.organisation))return response({error:'Source not authorised by accepted event policy'},403,origin);
 const committed=canonicalBytes(data);if(committed.length>4096)return response({error:'Canonical evidence package exceeds 4 KiB'},413,origin);const digest=await sha256(committed);const key=`evidence/${data.eventId}/${data.evidenceId}/${digest}.json`;const existing=await rows<{digest:string}>(env,`evidence_packages?evidence_id=eq.${data.evidenceId}&select=digest`);if(existing.length)return existing[0].digest===digest?response({evidenceId:data.evidenceId,eventId:data.eventId,organisation:data.organisation,type:data.type,observedAt:data.observedAt,targetEvidenceId:data.targetEvidenceId??'',digest,url:`${new URL(req.url).origin}/v1/evidence/${digest}`,packageBytes:committed.length,factCount:data.facts.length,duplicate:true},200,origin):response({error:'Evidence ID already committed'},409,origin);
 await env.EVIDENCE.put(key,committed,{httpMetadata:{contentType:'application/json'},customMetadata:{digest,event:data.eventId,organisation:data.organisation}});
 try{await db(env,'evidence_packages',{method:'POST',body:JSON.stringify({evidence_id:data.evidenceId,event_id:data.eventId,organisation_id:data.organisation,digest,object_key:key,source_type:data.type,observed_at:data.observedAt,package_bytes:committed.length,fact_count:data.facts.length})})}catch{await env.EVIDENCE.delete(key);throw Error('Index write failed; object rolled back')}
 return response({evidenceId:data.evidenceId,eventId:data.eventId,organisation:data.organisation,type:data.type,observedAt:data.observedAt,targetEvidenceId:data.targetEvidenceId??'',digest,url:`${new URL(req.url).origin}/v1/evidence/${digest}`,packageBytes:committed.length,factCount:data.facts.length,onchainCommitted:false},201,origin)}
async function evidenceBytes(digest:string,env:Env){if(!/^[0-9a-f]{64}$/.test(digest))return new Response('Invalid digest',{status:400});const matches=await rows<{object_key:string}>(env,`evidence_packages?digest=eq.${digest}&select=object_key`);if(matches.length!==1)return new Response('Unavailable',{status:404});const object=await env.EVIDENCE.get(matches[0].object_key);if(!object)return new Response('Unavailable',{status:404});const bytes=new Uint8Array(await object.arrayBuffer());if(await sha256(bytes)!==digest)return new Response('Integrity failure',{status:409});return new Response(bytes,{headers:{'content-type':'application/json','cache-control':'public,max-age=300,immutable','x-content-type-options':'nosniff','x-evidence-sha256':digest}})}
export async function indexOne(env:Env,hash:`0x${string}`){
 const client=chainClient(env);const tx=await client.getTransaction({hash:hash as any});if(!verifiedReceipt(tx))throw Error('Transaction is not finalized with successful execution');
 const identified=identifyIntentAcross(tx,contractMaps(env));const {method,args,eventId,contracts}=identified;const now=new Date().toISOString();
 await upsert(env,'tracked_transactions',{tx_hash:hash,event_id:eventId??null,contract_name:identified.contract,method_name:method,recipient:contracts[identified.contract]});
 if(method==='register'||method==='rotate_signer'){
  const id=String(args[0]);if(!/^[A-Za-z0-9_-]{1,64}$/.test(id))throw Error('Invalid organisation');
  const raw=await client.readContract({address:contracts.participants,functionName:'get',args:[id]});if(!raw)throw Error('Registration absent onchain');const record=JSON.parse(String(raw));if(method==='rotate_signer'&&String(record.signer).toLowerCase()!==String(args[1]).toLowerCase())throw Error('Signer rotation mismatch');
  await upsert(env,'indexed_organisations',{organisation_id:id,record,source_tx_hash:hash,verified_at:now});
 }else if(method==='propose_version'||method==='accept_version'){
  const id=String(args[0]),version=Number(method==='propose_version'?args[3]:args[1]);
  if(!/^[A-Za-z0-9_-]{1,64}$/.test(id)||!Number.isSafeInteger(version)||version<1)throw Error('Invalid agreement arguments');
  const raw=await client.readContract({address:contracts.agreements,functionName:'get_version',args:[id,BigInt(version)]});if(!raw)throw Error('Agreement absent onchain');
  const term=JSON.parse(String(raw));if(term.agreement!==id||term.version!==version)throw Error('Agreement mismatch');
  await upsert(env,'indexed_agreements',{agreement_id:id,version,operator_id:term.operator,counterparty_id:term.counterparty,accepted:term.accepted,policy:term.policy,source_tx_hash:hash,verified_at:now});
 }else{
  if(!eventId)throw Error('Missing event argument');
  const snapshot=await readVerifiedEvent(env,eventId,contracts);const {event,evidence,determination,effects}=snapshot;
  if(method==='submit'&&!evidence.some(x=>x.id===args[0]&&x.organisation===args[2]&&x.digest===args[4]))throw Error('Submitted record mismatch');
  if(method==='close_window'&&!snapshot.manifest.digest)throw Error('Manifest not frozen');
  if(method==='record_finalized'&&!determination)throw Error('Finalized child not delivered');
  if(method==='apply'&&!effects.some(x=>x.agreement===args[1]&&Number(x.version)===Number(args[2])))throw Error('Obligation absent');
  if(method==='claim'&&!effects.some(x=>x.agreement===args[1]&&Number(x.version)===Number(args[2])&&x.claim?.status==='CLAIMED'))throw Error('Claim absent');
  let stage=determination?'FINALIZED':snapshot.manifest.digest?'EVIDENCE_FROZEN':'OPEN';
  if((method==='determine'||method==='redeliver')&&!determination){const raw=await client.readContract({address:contracts.consensus,functionName:'get',args:[eventId]});if(!raw)throw Error('Consensus result absent');stage='FINALIZED_DELIVERY_PENDING';}
  await upsert(env,'indexed_events',{event_id:event.id,asset:event.asset,operator_id:event.operator,stage,cause:determination?.cause??null,parties:event.parties,links:event.links,close_after:event.closeAfter,opened_minute:event.openedMinute,source_tx_hash:hash,verified_at:now,updated_at:now,...(method==='determine'?{consensus_tx_hash:hash}:{}),...(method==='record_finalized'?{child_tx_hash:hash}:{})});
  if(method==='submit'){const item=evidence.find(x=>x.id===args[0]);await upsert(env,'indexed_evidence',{evidence_id:item.id,event_id:item.event,organisation_id:item.organisation,kind:item.kind,digest:item.digest,url:item.url,observed_at:item.observedAt,target_id:item.target||null,source_tx_hash:hash,verified_at:now})}
  if(determination&&method==='record_finalized')await upsert(env,'indexed_determinations',{event_id:event.id,cause:determination.cause,responsible_org:determination.responsible_org||null,start_minute:determination.start_minute,end_minute:determination.end_minute,result:determination,source_tx_hash:hash,verified_at:now});
  if(method==='apply')for(const item of effects.filter(x=>x.agreement===args[1]&&Number(x.version)===Number(args[2])))await upsert(env,'indexed_effects',{event_id:item.event,agreement_id:item.agreement,version:item.version,mode:item.mode,outcomes:item.outcomes,source_tx_hash:hash,verified_at:now});
  if(['close_window','determine','record_finalized','apply'].includes(method))for(const org of event.parties)await db(env,'notifications?on_conflict=notification_key',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates'},body:JSON.stringify({organisation_id:org,event_id:event.id,message:method==='record_finalized'?`Determination finalized: ${determination?.cause}`:method==='apply'?`Commercial effect recorded for ${String(args[1])}`:method==='close_window'?'Evidence window closed; ready for determination':'Consensus finalized; child delivery pending',notification_key:`${hash}:${org}`})});
 }
 let feeOutcome=null,rounds=null;try{const receipt=await rawReceipt(env,hash);if(String(receipt.recipient??receipt.to_address).toLowerCase()!==contracts[identified.contract].toLowerCase()||!verifiedReceipt(receipt))throw Error('Receipt status mismatch');feeOutcome=receipt.fees??null;rounds=receipt.roundData??receipt.round_data??receipt.consensus_history??(receipt.last_round?[receipt.last_round]:[])}catch(e){if(!/unavailable/i.test(String(e)))throw e}
 await upsert(env,'tracked_transactions',{tx_hash:hash,event_id:eventId??null,contract_name:identified.contract,method_name:method,recipient:contracts[identified.contract],verified_at:now,verified_execution:'FINISHED_WITH_RETURN',fee_outcome:feeOutcome,rounds,error:null});
 return {event:eventId??null,method};
}
export async function reconcile(env:Env){const pending=await rows<{tx_hash:`0x${string}`;event_id:string|null}>(env,'tracked_transactions?verified_at=is.null&select=tx_hash,event_id&limit=100');let verified=0;for(const row of pending){try{const indexed=await indexOne(env,row.tx_hash);verified++;if(indexed.method==='determine'||indexed.method==='redeliver'){const children=await chainClient(env).getTriggeredTransactionIds({hash:row.tx_hash as any});for(const child of children)await upsert(env,'tracked_transactions',{tx_hash:child,event_id:indexed.event})}}catch(e){await upsert(env,'index_failures',{tx_hash:row.tx_hash,reason:String(e),attempted_at:new Date().toISOString()});}}const deliveries=await rows<{event_id:string;consensus_tx_hash:string}>(env,'indexed_events?stage=eq.FINALIZED_DELIVERY_PENDING&select=event_id,consensus_tx_hash&limit=100');for(const d of deliveries){if(!d.consensus_tx_hash)continue;try{const children=await chainClient(env).getTriggeredTransactionIds({hash:d.consensus_tx_hash as any});for(const child of children)await upsert(env,'tracked_transactions',{tx_hash:child,event_id:d.event_id})}catch(e){await upsert(env,'index_failures',{tx_hash:d.consensus_tx_hash,reason:'Child discovery: '+String(e),attempted_at:new Date().toISOString()})}}return {scanned:pending.length,verified,deliveryPending:deliveries.length}}
export default {async fetch(req:Request,env:Env){const url=new URL(req.url),origin=req.headers.get('origin')===env.ALLOWED_ORIGIN?env.ALLOWED_ORIGIN:'';try{if(req.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'authorization,content-type,x-fieldledger-timestamp,x-fieldledger-signature'}});
 if(req.method==='POST'&&url.pathname==='/internal/index'){if(!env.INTERNAL_CRON_TOKEN||req.headers.get('authorization')!==`Bearer ${env.INTERNAL_CRON_TOKEN}`)return response({error:'Unauthorized'},401,origin);const body=await req.json() as {hash?:string};if(!/^0x[0-9a-fA-F]{64}$/.test(body.hash??''))return response({error:'Invalid transaction hash'},422,origin);const result=await indexOne(env,body.hash as `0x${string}`);if(result.event&&(result.method==='determine'||result.method==='redeliver')){const children=await chainClient(env).getTriggeredTransactionIds({hash:body.hash as any});for(const child of children)await upsert(env,'tracked_transactions',{tx_hash:child,event_id:result.event})}return response({indexed:true,...result},200,origin)}
 if(req.method==='GET'&&url.pathname==='/health')return response({service:'FIELDLEDGER gateway',chainId:61997},200,origin);
 if(req.method==='POST'&&url.pathname==='/v1/evidence/source')return await ingest(req,env,origin,false);
 if(req.method==='POST'&&url.pathname==='/v1/evidence/manual')return await ingest(req,env,origin,true);
 if(req.method==='GET'&&url.pathname.startsWith('/v1/evidence/'))return await evidenceBytes(url.pathname.split('/').pop()??'',env);
 const txMatch=url.pathname.match(/^\/v1\/transactions\/(0x[0-9a-fA-F]{64})$/);if(req.method==='GET'&&txMatch){const p=await principal(req,env);const data=await rows<any>(env,`tracked_transactions?tx_hash=eq.${txMatch[1]}&select=*`);if(data.length!==1||!data[0].event_id)return response({error:'Not found'},404,origin);const linked=await rows<any>(env,`indexed_events?event_id=eq.${data[0].event_id}&select=parties`);if(linked.length!==1||!linked[0].parties.some((org:string)=>membership(p,org)))return response({error:'Not found'},404,origin);return response(data[0],200,origin)}
 if(req.method==='POST'&&url.pathname==='/v1/transactions/track'){const p=await principal(req,env);if(!p.organisations.some(x=>['preparer','signer'].includes(x.application_role)))return response({error:'Role denied'},403,origin);const body=await req.json() as {hash?:string};if(!/^0x[0-9a-fA-F]{64}$/.test(body.hash??''))return response({error:'Invalid hash'},422,origin);const maps=contractMaps(env);const tx=await chainClient(env).getTransaction({hash:body.hash as any});const intent=identifyIntentAcross(tx,maps);if(intent.eventId){const snapshot=await readVerifiedEvent(env,intent.eventId,intent.contract==='events'||intent.contract==='evidence'||intent.contract==='consensus'||intent.contract==='obligations'?intent.contracts:undefined);if(!snapshot.event.parties.some((org:string)=>membership(p,org,true)))return response({error:'Event role denied'},403,origin)}await upsert(env,'tracked_transactions',{tx_hash:body.hash,event_id:intent.eventId??null,contract_name:intent.contract,method_name:intent.method,recipient:intent.contracts[intent.contract]});return response({tracked:true,eventId:intent.eventId??null},202,origin)}
 const protocolMatch=url.pathname.match(/^\/v1\/events\/([A-Za-z0-9_-]{1,64})\/protocol$/);
 if(req.method==='GET'&&protocolMatch){const p=await principal(req,env);const eventId=protocolMatch[1];const snapshot=await readVerifiedEvent(env,eventId);if(!snapshot.event.parties.some((org:string)=>membership(p,org)))return response({error:'Not found'},404,origin);const candidates=await rows<any>(env,`tracked_transactions?event_id=eq.${eventId}&select=tx_hash,method_name,rounds,fee_outcome,verified_at&limit=100`);const maps=contractMaps(env);const client=chainClient(env);const history=[];for(const row of candidates){const tx=await client.getTransaction({hash:row.tx_hash});if(row.method_name==='determine'||row.method_name==='redeliver'){const intent=assertDeterminationContext(tx,maps,eventId);let round=0,detail=null;try{const n=await client.getRoundNumber({txId:row.tx_hash});round=Number(n);detail=await client.getRoundData({txId:row.tx_hash,round:n})}catch{}history.push({hash:row.tx_hash,method:intent.method,status:tx.statusName,execution:tx.txExecutionResultName,round,detail,rounds:row.rounds,fees:row.fee_outcome})}}return response({eventId,history},200,origin)}
 if(req.method==='GET'&&url.pathname==='/v1/workspace'){const p=await principal(req,env);const [assets,notifications,savedViews]=await Promise.all([rows<any>(env,'assets?select=*'),rows<any>(env,'notifications?select=*&order=created_at.desc&limit=100'),rows<any>(env,`saved_views?user_id=eq.${p.userId}&select=*`)]);return response({assets:assets.filter(a=>membership(p,a.organisation_id)),notifications:notifications.filter(n=>membership(p,n.organisation_id)),savedViews},200,origin)}
 if(req.method==='POST'&&url.pathname==='/v1/assets'){const p=await principal(req,env);const a=await req.json() as Record<string,string>;if(!/^[A-Za-z0-9_-]{1,64}$/.test(a.asset_id||'')||!membership(p,a.organisation_id,true)||!['LOW','MEDIUM','HIGH','SAFETY_CRITICAL'].includes(a.criticality)||[a.description,a.equipment_class,a.facility].some(v=>!v||v.length>160))return response({error:'Asset or role invalid'},422,origin);await db(env,'assets',{method:'POST',body:JSON.stringify({asset_id:a.asset_id,organisation_id:a.organisation_id,description:a.description,equipment_class:a.equipment_class,facility:a.facility,criticality:a.criticality})});return response({created:true},201,origin)}
 if(req.method==='POST'&&url.pathname==='/v1/saved-views'){const p=await principal(req,env);const v=await req.json() as {name?:string;filter_json?:unknown};if(!v.name||v.name.length>100||!v.filter_json||typeof v.filter_json!=='object')return response({error:'Invalid view'},422,origin);await db(env,'saved_views',{method:'POST',body:JSON.stringify({user_id:p.userId,name:v.name,filter_json:v.filter_json})});return response({created:true},201,origin)}
 if(req.method==='POST'&&url.pathname==='/v1/notifications/read'){const p=await principal(req,env);const v=await req.json() as {id?:string};if(!/^[0-9a-f-]{36}$/.test(v.id||''))return response({error:'Invalid notification'},422,origin);const n=await rows<any>(env,`notifications?id=eq.${v.id}&select=organisation_id`);if(n.length!==1||!membership(p,n[0].organisation_id))return response({error:'Not found'},404,origin);await db(env,`notifications?id=eq.${v.id}`,{method:'PATCH',body:JSON.stringify({read_at:new Date().toISOString()})});return response({read:true},200,origin)}
 if(req.method==='GET'&&url.pathname==='/v1/catalogue'){const p=await principal(req,env);const [organisations,agreements]=await Promise.all([rows<any>(env,'indexed_organisations?select=*'),rows<any>(env,'indexed_agreements?select=*')]);return response({organisations:organisations.filter(x=>membership(p,x.organisation_id)),agreements:agreements.filter(x=>membership(p,x.operator_id)||membership(p,x.counterparty_id)),memberships:p.organisations},200,origin)}
 if(req.method==='GET'&&url.pathname==='/v1/events'){const p=await principal(req,env);const data=await rows<any>(env,'indexed_events?select=*&order=updated_at.desc&limit=100');return response(data.filter(e=>e.parties?.some((org:string)=>membership(p,org))),200,origin)}
 const match=url.pathname.match(/^\/v1\/events\/([A-Za-z0-9_-]{1,64})(\/export)?$/);
 if(req.method==='GET'&&match){const p=await principal(req,env);const event=await rows<any>(env,`indexed_events?event_id=eq.${match[1]}&select=*`);if(event.length!==1||!event[0].parties.some((org:string)=>membership(p,org)))return response({error:'Not found'},404,origin);const snapshot=await readVerifiedEvent(env,match[1]);if(event[0].cause && event[0].cause!==snapshot.determination?.cause)throw Error('Read model and chain disagree');const verifiedAt=new Date().toISOString();if(match[2]){const transactions=await rows<any>(env,`tracked_transactions?event_id=eq.${match[1]}&verified_at=not.is.null&select=tx_hash,recipient,method_name,verified_execution,fee_outcome,rounds&limit=100`);const maps=contractMaps(env),client=chainClient(env);for(const row of transactions){const verified=identifyIntentAcross(await client.getTransaction({hash:row.tx_hash as any}),maps);if(verified.eventId!==match[1]||verified.method!==row.method_name||verified.contracts[verified.contract].toLowerCase()!==String(row.recipient).toLowerCase())throw Error('Indexed receipt mismatch during export')}const pkg={format:'FIELDLEDGER decision package v1',network:61997,verifiedAt,...snapshot,verifiedTransactions:transactions};const bytes=canonicalBytes(pkg);const digest=await sha256(bytes);const key=`decisions/${match[1]}/${digest}.json`;await env.EVIDENCE.put(key,bytes,{httpMetadata:{contentType:'application/json'},customMetadata:{digest,event:match[1]}});await upsert(env,'decision_exports',{digest,event_id:match[1],object_key:key,created_by:p.userId});return response({...pkg,packageDigest:digest},200,origin)}return response({network:61997,verifiedAt,...snapshot},200,origin)}
 if(req.method==='POST'&&url.pathname==='/internal/reconcile'&&req.headers.get('authorization')===`Bearer ${env.INTERNAL_CRON_TOKEN}`)return response(await reconcile(env),200,origin);
 return response({error:'Not found'},404,origin)
 }catch(e){const message=String(e);return response({error:message},/Authentication|Invalid session/.test(message)?401:500,origin)}},async scheduled(_c:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil(reconcile(env))}};

export {verifiedReceipt} from './indexer';
export {adapters} from './adapters';
