import {createClient,chains} from 'genlayer-js';
export type ContractMap=Record<'participants'|'agreements'|'events'|'evidence'|'consensus'|'obligations',`0x${string}`>;
export const methodContract:Record<string,keyof ContractMap>={open_event:'events',challenge_event_envelope:'events',record_finalized:'events',submit:'evidence',close_window:'evidence',determine:'consensus',redeliver:'consensus',apply:'obligations',claim:'obligations',propose_version:'agreements',accept_version:'agreements',register:'participants',rotate_signer:'participants'};
export function verifiedReceipt(tx:any){const norm=(x:unknown)=>String(x??'').replace(/[^a-z]/gi,'').toLowerCase();return norm(tx?.statusName??tx?.status??tx?.status_name)==='finalized'&&norm(tx?.txExecutionResultName??tx?.tx_execution_result_name)==='finishedwithreturn'}
export function identifyIntent(tx:any,contracts:ContractMap){const call=tx.txDataDecoded?.callData as Record<string,unknown>|undefined;const method=call?.[''];const args=call?.args;if(typeof method!=='string'||!Array.isArray(args)||!methodContract[method])throw Error('Unrecognized method');const contract=methodContract[method];if(String(tx.recipient??'').toLowerCase()!==contracts[contract].toLowerCase())throw Error('Recipient is not the configured contract');let eventId:string|undefined;if(['open_event','challenge_event_envelope','close_window','determine','redeliver','record_finalized','apply','claim'].includes(method))eventId=String(args[0]);if(method==='submit')eventId=String(args[1]);if(eventId&&!/^[A-Za-z0-9_-]{1,64}$/.test(eventId))throw Error('Invalid event argument');return {contract,method,args,eventId};}
export function identify(tx:any,contracts:ContractMap){if(!verifiedReceipt(tx))throw Error('Transaction is not finalized with successful execution');return identifyIntent(tx,contracts)}
export function assertDeterminationContext(tx:any,contracts:ContractMap,eventId:string){const intent=identifyIntent(tx,contracts);if(intent.eventId!==eventId||intent.contract!=='consensus'||!['determine','redeliver'].includes(intent.method))throw Error('Transaction is not this event determination');return intent}
export interface IndexEnv{GENLAYER_RPC:string;CONTRACTS_JSON:string}
export function chainClient(env:IndexEnv){return createClient({chain:chains.studioDevnet,endpoint:env.GENLAYER_RPC})}
export async function readVerifiedEvent(env:IndexEnv,eventId:string){const addresses=JSON.parse(env.CONTRACTS_JSON) as ContractMap;const client=chainClient(env);const raw=await client.readContract({address:addresses.events,functionName:'get',args:[eventId]});if(!raw||typeof raw!=='string')throw Error('Event unavailable onchain');const event=JSON.parse(raw);if(event.id!==eventId)throw Error('Event ID mismatch');const manifest=JSON.parse(String(await client.readContract({address:addresses.evidence,functionName:'manifest',args:[eventId]})));const evidence=[];for(const id of manifest.ids){const r=await client.readContract({address:addresses.evidence,functionName:'get',args:[id]});if(r)evidence.push(JSON.parse(String(r)))}const effects=[];for(const link of event.links){const rawEffect=await client.readContract({address:addresses.obligations,functionName:'get',args:[eventId,link.id,BigInt(link.version)]});if(rawEffect){const item=JSON.parse(String(rawEffect));const claim=await client.readContract({address:addresses.obligations,functionName:'get_claim',args:[eventId,link.id,BigInt(link.version)]});item.claim=claim?JSON.parse(String(claim)):null;effects.push(item)}}return {event,manifest,evidence,effects,determination:event.finalResult?JSON.parse(event.finalResult):null};}

export async function rawReceipt(env:IndexEnv,hash:string){const r=await fetch(env.GENLAYER_RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_getTransactionByHash',params:[hash]})});if(!r.ok)throw Error('Transaction RPC unavailable');const body=await r.json() as {result?:any;error?:unknown};const tx=body.result;if(body.error||!tx||String(tx.hash??tx.tx_id??'').toLowerCase()!==hash.toLowerCase())throw Error('Transaction unavailable or mismatched');return tx}
