import {abi,createClient,chains} from 'genlayer-js';
export type ContractMap=Record<'participants'|'agreements'|'events'|'evidence'|'consensus'|'obligations',`0x${string}`>;
export interface IndexEnv{GENLAYER_RPC:string;CONTRACTS_JSON:string;CONTRACTS_ARCHIVE_JSON?:string}
export function contractMaps(env:IndexEnv):ContractMap[]{const active=JSON.parse(env.CONTRACTS_JSON) as ContractMap;const archived=env.CONTRACTS_ARCHIVE_JSON?JSON.parse(env.CONTRACTS_ARCHIVE_JSON) as ContractMap[]:[];if(!Array.isArray(archived))throw Error('CONTRACTS_ARCHIVE_JSON must be a JSON array of prior contract maps');const all=[active,...archived],seen=new Set<string>(),unique:ContractMap[]=[];for(const map of all){for(const name of ['participants','agreements','events','evidence','consensus','obligations'] as const)if(!/^0x[0-9a-fA-F]{40}$/.test(map?.[name]??''))throw Error('Invalid contract map');const key=['participants','agreements','events','evidence','consensus','obligations'].map(name=>map[name as keyof ContractMap].toLowerCase()).join(':');if(!seen.has(key)){seen.add(key);unique.push(map)}}return unique}
export const methodContract:Record<string,keyof ContractMap>={open_event:'events',challenge_event_envelope:'events',record_finalized:'events',submit:'evidence',close_window:'evidence',determine:'consensus',redeliver:'consensus',apply:'obligations',claim:'obligations',propose_version:'agreements',accept_version:'agreements',register:'participants',rotate_signer:'participants'};
export function verifiedReceipt(tx:any){const norm=(x:unknown)=>String(x??'').replace(/[^a-z]/gi,'').toLowerCase();return norm(tx?.statusName??tx?.status??tx?.status_name)==='finalized'&&norm(tx?.txExecutionResultName??tx?.tx_execution_result_name)==='finishedwithreturn'}
export function identifyIntent(tx:any,contracts:ContractMap){let call=tx.txDataDecoded?.callData as Record<string,unknown>|undefined;if(!call){const raw=tx.data?.calldata?.raw;if(!Array.isArray(raw)||raw.length>65536||raw.some((byte:unknown)=>!Number.isInteger(byte)||Number(byte)<0||Number(byte)>255))throw Error('Unrecognized method');const decoded=abi.calldata.decode(Uint8Array.from(raw)) as unknown;if(decoded instanceof Map)call=Object.fromEntries(decoded) as Record<string,unknown>;else if(decoded&&typeof decoded==='object'&&!Array.isArray(decoded))call=decoded as Record<string,unknown>;}const method=call?.[''];const args=call?.args;if(typeof method!=='string'||!Array.isArray(args)||!methodContract[method])throw Error('Unrecognized method');const contract=methodContract[method];if(String(tx.recipient??tx.to_address??'').toLowerCase()!==contracts[contract].toLowerCase())throw Error('Recipient is not the configured contract');let eventId:string|undefined;if(['open_event','challenge_event_envelope','close_window','determine','redeliver','record_finalized','apply','claim'].includes(method))eventId=String(args[0]);if(method==='submit')eventId=String(args[1]);if(eventId&&!/^[A-Za-z0-9_-]{1,64}$/.test(eventId))throw Error('Invalid event argument');return {contract,method,args,eventId};}
export function identifyIntentAcross(tx:any,maps:ContractMap[]){let lastError:unknown;for(const contracts of maps){try{return {...identifyIntent(tx,contracts),contracts}}catch(error){lastError=error}}if(lastError)throw lastError;throw Error('No contract generations configured')}
export function identify(tx:any,contracts:ContractMap){if(!verifiedReceipt(tx))throw Error('Transaction is not finalized with successful execution');return identifyIntent(tx,contracts)}
export function assertDeterminationContext(tx:any,contracts:ContractMap|ContractMap[],eventId:string){const intent=identifyIntentAcross(tx,Array.isArray(contracts)?contracts:[contracts]);if(intent.eventId!==eventId||intent.contract!=='consensus'||!['determine','redeliver'].includes(intent.method))throw Error('Transaction is not this event determination');return intent}
export function chainClient(env:IndexEnv){return createClient({chain:chains.studioDevnet,endpoint:env.GENLAYER_RPC})}
export async function readVerifiedEvent(env:IndexEnv,eventId:string,preferred?:ContractMap){const client=chainClient(env);const maps=preferred?[preferred]:contractMaps(env);const matches:Array<{contracts:ContractMap;event:any}>=[];for(const addresses of maps){const raw=await client.readContract({address:addresses.events,functionName:'get',args:[eventId]});if(!raw||typeof raw!=='string')continue;const candidate=JSON.parse(raw);if(candidate.id===eventId)matches.push({contracts:addresses,event:candidate})}if(!matches.length)throw Error('Event unavailable in configured contract generations');if(matches.length>1)throw Error('Ambiguous event ID across contract generations');const {contracts:addresses,event}=matches[0];const manifest=JSON.parse(String(await client.readContract({address:addresses.evidence,functionName:'manifest',args:[eventId]})));const evidence=[];for(const id of manifest.ids){const r=await client.readContract({address:addresses.evidence,functionName:'get',args:[id]});if(r)evidence.push(JSON.parse(String(r)))}const effects=[];for(const link of event.links){const rawEffect=await client.readContract({address:addresses.obligations,functionName:'get',args:[eventId,link.id,BigInt(link.version)]});if(rawEffect){const item=JSON.parse(String(rawEffect));const claim=await client.readContract({address:addresses.obligations,functionName:'get_claim',args:[eventId,link.id,BigInt(link.version)]});item.claim=claim?JSON.parse(String(claim)):null;effects.push(item)}}return {event,manifest,evidence,effects,determination:event.finalResult?JSON.parse(event.finalResult):null,contracts:addresses};}

export async function rawReceipt(env:IndexEnv,hash:string){const r=await fetch(env.GENLAYER_RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_getTransactionByHash',params:[hash]})});if(!r.ok)throw Error('Transaction RPC unavailable');const body=await r.json() as {result?:any;error?:unknown};const tx=body.result;if(body.error||!tx||String(tx.hash??tx.tx_id??'').toLowerCase()!==hash.toLowerCase())throw Error('Transaction unavailable or mismatched');return tx}
